# Generated by Django 4.2.30 on 2026-10-09 00:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


def initialize_occurrences(apps, schema_editor):
    # AddField's callable default is evaluated once for existing rows. Assign
    # each queued/playing occurrence its own identity before importing votes.
    for name in ("QueuedSong", "CurrentSong"):
        model = apps.get_model("core", name)
        for key in model.objects.using(schema_editor.connection.alias).values_list("pk", flat=True).iterator():
            model.objects.using(schema_editor.connection.alias).filter(pk=key).update(occurrence_id=uuid.uuid4())
    apps.get_model("core", "QueueMutationLock").objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_furatic_moderation_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_id', models.UUIDField(unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(db_index=True)),
                ('artist', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('external_url', models.CharField(max_length=2000)),
                ('artwork_url', models.CharField(blank=True, default='', max_length=2000)),
                ('duration', models.FloatField()),
                ('votes', models.IntegerField(default=0)),
                ('outcome', models.CharField(default='completed', max_length=20)),
            ],
            options={
                'ordering': ['-ended_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QueueMutationLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SongVoteState',
            fields=[
                ('occurrence_id', models.UUIDField(primary_key=True, serialize=False)),
                ('engagement', models.JSONField(default=dict)),
                ('retired_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='currentsong',
            name='occurrence_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='currentsong',
            name='playback_outcome',
            field=models.CharField(default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='currentsong',
            name='playback_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuedsong',
            name='occurrence_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='VoteMutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_key', models.CharField(max_length=80)),
                ('mutation_id', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='core.songvotestate')),
            ],
        ),
        migrations.CreateModel(
            name='SongVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_key', models.CharField(max_length=80)),
                ('choice', models.SmallIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('changed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activity_recorded', models.BooleanField(default=False)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='core.songvotestate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='votemutation',
            constraint=models.UniqueConstraint(fields=('occurrence', 'voter_key', 'mutation_id'), name='unique_vote_mutation'),
        ),
        migrations.AddIndex(
            model_name='songvote',
            index=models.Index(fields=['voter_key', 'changed_at'], name='song_voter_activity'),
        ),
        migrations.AddConstraint(
            model_name='songvote',
            constraint=models.UniqueConstraint(fields=('occurrence', 'voter_key'), name='unique_song_voter'),
        ),
        migrations.RunPython(initialize_occurrences, migrations.RunPython.noop),
    ]
